name: Deploy to Server

on:
  push:
    branches:
      - main  # Замените на вашу основную ветку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to server
        run: |
          ssh ubuntu@54.83.180.49 "
          cd orden &&
          git pull origin main &&
          cd cmd &&
          go build -o app main.go &&
          systemctl restart goweb.service
        "