env:
  SYSTEMD_UNIT: ${{ secrets.SYSTEMD_UNIT }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_IP: ${{ secrets.SERVER_IP }}
  BRANCH_NAME: ${{ secrets.BRANCH_NAME }}
  PROJECT_DIR: ${{ secrets.PROJECT_DIR }}
  SYSTEMD_UNIT: ${{ secrets.SYSTEMD_UNIT }}


name: Deploy to Server

on:
  push:
    branches:
      - $BRANCH_NAME 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
          cd $PROJECT_DIR &&
          git pull origin $BRANCH_NAME &&
          cd cmd &&
          go build main.go &&
          sudo systemctl restart $SYSTEMD_UNIT 
          "